# config file

dataset:
  h5_path: data/rmsc.h5
  data_path: data/rmsc.pickle
  meta_data_path: data/rmsc.pickle.meta
  doc_rep_path: data/rmsc_doc_qt_rep.pt

global:
  random_seed: 123
  num_data_workers: 16

  max_sent_length: 20
  max_sent_num: 40
  cand_doc_size: 4

model:
  embedding_dim: 100
  hidden_size: 100
  label_size: 22
  dropout_p: 0.2
  layer_norm: false

train:
  num_epochs: 20
  train_iters: 5000
  valid_iters: 100
  test_iters: 1000

  eval_steps: 100
  save_steps: 1000

  batch_size: 32
  optimizer: adamax   # adam, sgd, adamax
  learning_rate: 0.001
  clip_grad_norm: 5