# python logging config file

version: 1
disable_existing_loggers: False

formatters:
    simple:
        format: "%(asctime)s - [%(filename)s:%(lineno)s-%(funcName)s()] - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: outputs/default/debug.log     # re-defined in code
        maxBytes: 30485760 # 30MB
        backupCount: 20
        encoding: utf8
    time_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: outputs/default/debug.log     # re-defined in code
        backupCount: 20000
        when: midnight
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: outputs/default/errors.log    # re-defined in code
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler]